Documentation:
   Enabled: false
LineLength:
   Max: 1000
Style/FrozenStringLiteralComment:
   Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
    Enabled: false