language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_install:
  - psql -c 'CREATE DATABASE myapp_test;' -U postgres
  - psql -c "CREATE USER \"wbooks-api\" WITH PASSWORD 'wbooks-api';" -U postgres
  - bundle install
  - bundle exec bin/rails db:migrate RAILS_ENV=test

script:
  - bundle exec rubocop spec app -R
  - bundle exec rspec

cache:
  bundler: true