language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_install:
  - psql -c 'CREATE DATABASE myapp_test;' -U postgres
  - psql -c "CREATE USER \"wbooks-api\" WITH PASSWORD 'wbooks-api';" -U postgres

script:
  - bundle exec rubocop app -R
  - bundle exec rspec

cache:
  bundler: true